### ISSUE TITLE
DataDragon GetRunes and GetMasteries are returning old ones

### ISSUE THREAD

**Issue by davidbayo10** [KnutZuidema/golio#43]
Those methods are returning old runes and masteries. Does this package support runes reforged?

**Comment by KnutZuidema** [comment]
AFAIK, there is no data about runes reforged available through data dragon.
The methods for runes and masteries use the newest version where they were still available, which is 7.23.1.

**Comment by davidbayo10** [comment]
I think those runes and masteries are deprecated. For the latest version of runes, It should be used http://ddragon.leagueoflegends.com/cdn/11.3.1/data/en_US/runesReforged.json. Is this library unmaintained? I noticed about some errors like, if you try to search champions by name the ID is used instead of Key for performing that search.

**Comment by KnutZuidema** [comment]
I am aware that they are deprecated, however the library should still provide access to the latest data available.
I don't actively develop this at the moment. I'm happy to review and merge PRs and work on issues that can be quickly fixed.

**Comment by davidbayo10** [comment]
Good to know! Thank you!
