### ISSUE TITLE
VAL endpoints

### ISSUE THREAD

**Issue by yigithanbalci** [KnutZuidema/golio#53]
There are some endpoints related to the valorant data ([VAL-CONTENT-V1](https://developer.riotgames.com/apis#val-content-v1), [VAL-MATCH-V1](https://developer.riotgames.com/apis#val-match-v1), [VAL-RANKED-V1](https://developer.riotgames.com/apis#val-ranked-v1), [VAL-STATUS-V1](https://developer.riotgames.com/apis#val-status-v1)) that can be added.

**Comment by KnutZuidema** [comment]
resolved by #54
