### ISSUE TITLE
Support for RiotID

### ISSUE THREAD

**Issue by Nico-Mayer** [KnutZuidema/golio#61]
Hey, first of all, great work on building this library. I'm wondering if there are plans to update the project to support the new Riot ID system with the `Summonername#tag` syntax in the future. Keep up the excellent work.

Best regards,
Nico

**Comment by KnutZuidema** [comment]
I am not actively working on this project, but I'm happy to support PRs adding new features or other improvements.

**Comment by harmonherring** [comment]
@Nico-Mayer Does the recent merge of #60 close this issue?
