### ISSUE TITLE
Introducing better documentation

### ISSUE THREAD

**Issue by happsie** [KnutZuidema/golio#72]
Most popular libraries and frameworks usually provide an extensive third party documenation resource. I think this could really help this great library in standing out amongst other Riot Games API libraries. This is just my opinion, but I find a library a bit more serious providing a proper documentation.  

I do like the option we are given using godoc and the possibility to have it generated automatic from the source code. But it's also very limiting in what we can do and provide to users. I will list some great libraries that could be easily adapted for github pages:

- [Docsify](https://docsify.js.org/#/)
- [Docusaurus](https://docusaurus.io/docs)

Let me know what you think!

**Comment by KnutZuidema** [comment]
Personally I have no interest in adding documentation, apart from godoc. I don't really see the point. This is a pure Go library, meaning it will only be used by Go developers. Godoc seems like the most fitting place for documentation.

If you could point out some specific limitation of godoc that would improve the library in some way, we can talk about that.
